spring:
  application:
    name: JavaServer_Movie_Ticket
    
open:
  api:
    title: API Document
    version: v1.0.0
    description: Mota API Service
    serverUrl: http://localhost:9011/
    serverName: Server Spring Boot